const collegesList = [
  {
    name: "Punjab Group of Colleges",
    main_campus: "Lahore",
    sub_campuses: ["Lahore", "Faisalabad", "Multan", "Karachi", "Islamabad"],
  },
  {
    name: "Superior Group of Colleges",
    main_campus: "Lahore",
    sub_campuses: ["Lahore", "Faisalabad", "Multan", "Karachi", "Islamabad"],
  },
  {
    name: "The Educators College",
    main_campus: "Lahore",
    sub_campuses: ["Lahore", "Faisalabad", "Multan", "Karachi", "Islamabad"],
  },
  { name: "Nixor College", main_campus: "Karachi", sub_campuses: [] },
  {
    name: "Indus Valley School of Art and Architecture",
    main_campus: "Karachi",
    sub_campuses: [],
  },
  {
    name: "Shaheed Zulfikar Ali Bhutto Institute of Science and Technology",
    main_campus: "Karachi",
    sub_campuses: [],
  },
  {
    name: "Institute of Business Administration",
    main_campus: "Karachi",
    sub_campuses: [],
  },
  { name: "Bahria University", main_campus: "Karachi", sub_campuses: [] },
  {
    name: "The Millennium Universal College",
    main_campus: "Islamabad",
    sub_campuses: [],
  },
  {
    name: "Riphah International College",
    main_campus: "Islamabad",
    sub_campuses: [],
  },
  {
    name: "FAST College",
    main_campus: "Islamabad",
    sub_campuses: [],
  },
  {
    name: "Beaconhouse",
    main_campus: "Lahore",
    sub_campuses: ["Lahore", "Multan", "Khushab"],
  },
  {
    name: "The Government College For Boys",
    main_campus: "Lahore",
    sub_campuses: [
      "Lahore",
      "Multan",
      "Sialkot",
      "Bahawalpur",
      "Rawalpindi",
      "Gujrat",
      "Jhang",
      "Layyah",
      "Rahim Yar Khan",
      "Sahiwal",
      "Vehari",
      "Narowal",
      "Khushab",
      "Mianwali",
      "Toba Tek Singh",
      "Attock",
    ],
  },
  {
    name: "Government College for Girls",
    main_campus: "Lahore",
    sub_campuses: [
      "Lahore",
      "Multan",
      "Sialkot",
      "Bahawalpur",
      "Rawalpindi",
      "Gujrat",
      "Jhang",
      "Layyah",
      "Rahim Yar Khan",
      "Sahiwal",
      "Vehari",
      "Narowal",
      "Khushab",
      "Mianwali",
      "Toba Tek Singh",
      "Attock",
    ],
  },
];

export default collegesList;
