const degreeSchemas = [
  {
    name: "Bachelor of Science in Computer Science",
    duration: "4 years",
    totalCreditHoursRequired: 100,
    semester_courses: [
      {
        semester: 1,
        courses: [
          {
            course_code: "CS101",
            course_name: "Introduction to Computer Science",
            credit_hours: 3,
            elective: false,
            prerequisites: [],
          },
          {
            course_code: "MATH101",
            course_name: "Calculus I",
            credit_hours: 3,
            elective: false,
            prerequisites: [],
          },
          {
            course_code: "ENG101",
            course_name: "English Composition",
            credit_hours: 3,
            elective: false,
            prerequisites: [],
          },
          {
            course_code: "SCI101",
            course_name: "Natural Sciences",
            credit_hours: 3,
            elective: false,
            prerequisites: [],
          },
          {
            course_code: "PAK101",
            course_name: "Pakistan Studies",
            credit_hours: 2,
            elective: false,
            prerequisites: [],
          },
        ],
      },
      {
        semester: 2,
        courses: [
          {
            course_code: "CS102",
            course_name: "Programming Fundamentals",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS101"],
          },
          {
            course_code: "MATH102",
            course_name: "Calculus II",
            credit_hours: 3,
            elective: false,
            prerequisites: ["MATH101"],
          },
          {
            course_code: "STAT101",
            course_name: "Statistics",
            credit_hours: 3,
            elective: false,
            prerequisites: [],
          },
          {
            course_code: "HUM101",
            course_name: "Humanities Elective",
            credit_hours: 3,
            elective: true,
            prerequisites: [],
          },
          {
            course_code: "ISL101",
            course_name: "Islamic Studies",
            credit_hours: 2,
            elective: false,
            prerequisites: [],
          },
        ],
      },
      {
        semester: 3,
        courses: [
          {
            course_code: "CS201",
            course_name: "Data Structures and Algorithms",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS102"],
          },
          {
            course_code: "CS202",
            course_name: "Computer Organization",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS102"],
          },
          {
            course_code: "MATH201",
            course_name: "Discrete Mathematics",
            credit_hours: 3,
            elective: false,
            prerequisites: ["MATH102"],
          },
          {
            course_code: "SOC101",
            course_name: "Social Sciences Elective",
            credit_hours: 3,
            elective: true,
            prerequisites: [],
          },
        ],
      },
      {
        semester: 4,
        courses: [
          {
            course_code: "CS301",
            course_name: "Database Systems",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS201"],
          },
          {
            course_code: "CS302",
            course_name: "Operating Systems",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS202"],
          },
          {
            course_code: "CS303",
            course_name: "Software Engineering",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS201"],
          },
          {
            course_code: "CS304",
            course_name: "Web Development",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS102"],
          },
        ],
      },
      {
        semester: 5,
        courses: [
          {
            course_code: "CS401",
            course_name: "Computer Networks",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS302"],
          },
          {
            course_code: "CS402",
            course_name: "Algorithm Design and Analysis",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS201"],
          },
          {
            course_code: "CS403",
            course_name: "Operating Systems II",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS302"],
          },
          {
            course_code: "ECON101",
            course_name: "Economics",
            credit_hours: 3,
            elective: true,
            prerequisites: [],
          },
        ],
      },
      {
        semester: 6,
        courses: [
          {
            course_code: "CS501",
            course_name: "Artificial Intelligence",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS402"],
          },
          {
            course_code: "CS502",
            course_name: "Compiler Construction",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS201"],
          },
          {
            course_code: "CS503",
            course_name: "Computer Graphics",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS302"],
          },
          {
            course_code: "ETH101",
            course_name: "Ethics",
            credit_hours: 3,
            elective: true,
            prerequisites: [],
          },
        ],
      },
      {
        semester: 7,
        courses: [
          {
            course_code: "CS601",
            course_name: "Software Testing and Quality Assurance",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS303"],
          },
          {
            course_code: "CS602",
            course_name: "Distributed Systems",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS301"],
          },
          {
            course_code: "CS603",
            course_name: "Cloud Computing",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS301"],
          },
          {
            course_code: "CS604",
            course_name: "Mobile Application Development",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS304"],
          },
        ],
      },
      {
        semester: 8,
        courses: [
          {
            course_code: "CS701",
            course_name: "Final Year Project",
            credit_hours: 6,
            elective: false,
            prerequisites: ["CS303"],
          },
          {
            course_code: "CS702",
            course_name: "Professional Practice",
            credit_hours: 3,
            elective: false,
            prerequisites: [],
          },
          {
            course_code: "CS703",
            course_name: "Cyber Security",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS402"],
          },
          {
            course_code: "CS704",
            course_name: "Big Data Analytics",
            credit_hours: 4,
            elective: false,
            prerequisites: ["CS301"],
          },
        ],
      },
    ],
  },
  {
    NamedNodeMap: "Bachelor of Software Engineering",
    duration: "4 years",
    totalCreditHoursRequired: 100,
    semester_courses: [
      {
        semester: 1,
        courses: [
          {
            course_code: "SE101",
            course_name: "Introduction to Software Engineering",
            credit_hours: 3,
            elective: false,
            prerequisites: [],
          },
          {
            course_code: "MATH101",
            course_name: "Calculus I",
            credit_hours: 3,
            elective: false,
            prerequisites: [],
          },
          {
            course_code: "ENG101",
            course_name: "English Composition",
            credit_hours: 3,
            elective: false,
            prerequisites: [],
          },
          {
            course_code: "SCI101",
            course_name: "Natural Sciences",
            credit_hours: 3,
            elective: false,
            prerequisites: [],
          },
          {
            course_code: "PAK101",
            course_name: "Pakistan Studies",
            credit_hours: 2,
            elective: false,
            prerequisites: [],
          },
        ],
      },
      {
        semester: 2,
        courses: [
          {
            course_code: "SE102",
            course_name: "Software Requirements Engineering",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE101"],
          },
          {
            course_code: "MATH102",
            course_name: "Calculus II",
            credit_hours: 3,
            elective: false,
            prerequisites: ["MATH101"],
          },
          {
            course_code: "STAT101",
            course_name: "Statistics",
            credit_hours: 3,
            elective: false,
            prerequisites: [],
          },
          {
            course_code: "HUM101",
            course_name: "Humanities Elective",
            credit_hours: 3,
            elective: true,
            prerequisites: [],
          },
          {
            course_code: "ISL101",
            course_name: "Islamic Studies",
            credit_hours: 2,
            elective: false,
            prerequisites: [],
          },
        ],
      },
      {
        semester: 3,
        courses: [
          {
            course_code: "SE201",
            course_name: "Software Design and Architecture",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE102"],
          },
          {
            course_code: "CS202",
            course_name: "Computer Organization",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE102"],
          },
          {
            course_code: "MATH201",
            course_name: "Discrete Mathematics",
            credit_hours: 3,
            elective: false,
            prerequisites: ["MATH102"],
          },
          {
            course_code: "SOC101",
            course_name: "Social Sciences Elective",
            credit_hours: 3,
            elective: true,
            prerequisites: [],
          },
        ],
      },
      {
        semester: 4,
        courses: [
          {
            course_code: "SE301",
            course_name: "Software Testing and Quality Assurance",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE201"],
          },
          {
            course_code: "SE302",
            course_name: "Software Project Management",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE201"],
          },
          {
            course_code: "SE303",
            course_name: "Software Metrics and Quality Management",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE201"],
          },
          {
            course_code: "CS304",
            course_name: "Web Development",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE102"],
          },
        ],
      },
      {
        semester: 5,
        courses: [
          {
            course_code: "SE401",
            course_name: "Software Design Patterns",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE301"],
          },
          {
            course_code: "SE402",
            course_name: "Software Architecture and Modeling",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE301"],
          },
          {
            course_code: "SE403",
            course_name: "Software Development Tools",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE301"],
          },
          {
            course_code: "ECON101",
            course_name: "Economics",
            credit_hours: 3,
            elective: true,
            prerequisites: [],
          },
        ],
      },
      {
        semester: 6,
        courses: [
          {
            course_code: "SE501",
            course_name: "Software Security",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE302"],
          },
          {
            course_code: "SE502",
            course_name: "Software Maintenance and Evolution",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE201"],
          },
          {
            course_code: "SE503",
            course_name: "Software Requirements Management",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE301"],
          },
          {
            course_code: "ETH101",
            course_name: "Ethics",
            credit_hours: 3,
            elective: true,
            prerequisites: [],
          },
        ],
      },
      {
        semester: 7,
        courses: [
          {
            course_code: "SE601",
            course_name: "Software Development Frameworks",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE401"],
          },
          {
            course_code: "SE602",
            course_name: "Software Process Improvement",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE301"],
          },
          {
            course_code: "SE603",
            course_name: "Software Quality Assurance",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE301"],
          },
          {
            course_code: "SE604",
            course_name: "Software Engineering Seminar",
            credit_hours: 2,
            elective: false,
            prerequisites: ["SE401"],
          },
        ],
      },
      {
        semester: 8,
        courses: [
          {
            course_code: "SE701",
            course_name: "Final Year Project",
            credit_hours: 6,
            elective: false,
            prerequisites: ["SE301"],
          },
          {
            course_code: "SE702",
            course_name: "Professional Practice",
            credit_hours: 3,
            elective: false,
            prerequisites: [],
          },
          {
            course_code: "SE703",
            course_name: "Advanced Software Engineering Topics",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE401"],
          },
          {
            course_code: "SE704",
            course_name: "Software Development Project Management",
            credit_hours: 4,
            elective: false,
            prerequisites: ["SE302"],
          },
        ],
      },
    ],
  },
];

export default degreeSchemas;
