const schoolsName = [
  { name: "Beaconhouse School System", city: "Multiple Cities" },
  { name: "The City School", city: "Multiple Cities" },
  { name: "Roots Millennium Schools", city: "Multiple Cities" },
  { name: "Lahore Grammar School", city: "Lahore" },
  { name: "Sadiq Public School", city: "Bahawalpur" },
  { name: "Convent of Jesus and Mary", city: "Multiple Cities" },
  { name: "Froebel's International School", city: "Islamabad" },
  { name: "Bay View High School", city: "Karachi" },
  { name: "Bloomfield Hall School", city: "Lahore" },
  { name: "International School of Choueifat", city: "Lahore" },
  { name: "Nixor College", city: "Karachi" },
  { name: "The Educators", city: "Multiple Cities" },
  { name: "KIPS Education System", city: "Lahore" },
  { name: "The Punjab School", city: "Lahore" },
  {
    name: "Pak Turk International Schools and Colleges",
    city: "Multiple Cities",
  },
  { name: "LACAS", city: "Lahore" },
  { name: "Beaconhouse Newlands", city: "Lahore" },
  { name: "Divisional Public School", city: "Lahore" },
  { name: "Roots School System", city: "Multiple Cities" },
  { name: "The Smart School", city: "Multiple Cities" },
  { name: "Allied School", city: "Multiple Cities" },
  {
    name: "Pak Turk Maarif International Schools & Colleges",
    city: "Multiple Cities",
  },
  { name: "Government Central Model School", city: "Lahore" },
  { name: "Government College University Model High School", city: "Lahore" },
  { name: "Government College University Model School", city: "Lahore" },
  { name: "Government Comprehensive Girls High School", city: "Karachi" },
  { name: "Government Degree College", city: "Karachi" },
  { name: "Government High School", city: "Islamabad" },
  { name: "Government Girls High School", city: "Islamabad" },
  { name: "Government Pilot Secondary School", city: "Karachi" },
  { name: "Government High School No. 1", city: "Karachi" },
  { name: "Government Higher Secondary School", city: "Karachi" },
];

export default schoolsName;
